import { MfeManifest } from './types';

export const MFE_REGISTRY: MfeManifest[] = [
  {
    id: 'mfe-employee-portal',
    name: 'MFE Employee Portal & Self Service',
    version: 'v2.4.0-remote',
    remoteEntryUrl: 'https://cdn.mfe.company.internal/remotes/employee/remoteEntry.js',
    scope: 'EMPLOYEE',
    title: 'Portal Karyawan & WFH Presensi',
    description: 'Modul independen untuk presensi WFH, foto selfie GPS, riwayat absensi, dan permohonan cuti/tukar hari.',
    iconName: 'UserCheck',
    routeKey: 'EMPLOYEE_MFE',
    subRoutes: [
      { key: 'ABSENSI_WFH', label: 'Clock In / Out WFH', icon: 'Clock', permission: 'CLOCK_IN_WFH' },
      { key: 'HISTORY_SAYA', label: 'Riwayat Presensi Saya', icon: 'Calendar', permission: 'VIEW_PERSONAL_HISTORY' },
      { key: 'PENGAJUAN_CUTI', label: 'Pengajuan Cuti & WFH', icon: 'CalendarDays', permission: 'MANAGE_LEAVE_REQUESTS' },
    ],
    status: 'HEALTHY',
    bundleSizeKb: 142.8,
    latencyMs: 18,
  },
  {
    id: 'mfe-hrd-analytics',
    name: 'MFE HRD Monitoring & Workforce Analytics',
    version: 'v3.1.2-remote',
    remoteEntryUrl: 'https://cdn.mfe.company.internal/remotes/hrd/remoteEntry.js',
    scope: 'HRD',
    title: 'Monitoring HRD & Master Karyawan',
    description: 'Modul analitik real-time pemantauan presensi karyawan, verifikasi foto On-Site/WFH, dan database pegawai.',
    iconName: 'Shield',
    routeKey: 'HRD_ANALYTICS_MFE',
    subRoutes: [
      { key: 'MONITORING_HRD', label: 'Monitoring Realtime HRD', icon: 'Activity', permission: 'VIEW_HRD_MONITORING' },
      { key: 'MASTER_KARYAWAN', label: 'Master Data Karyawan', icon: 'Users', permission: 'MANAGE_EMPLOYEES' },
    ],
    status: 'HEALTHY',
    bundleSizeKb: 218.4,
    latencyMs: 24,
  },
  {
    id: 'mfe-admin-governance',
    name: 'MFE Enterprise Governance & Payroll',
    version: 'v1.8.5-remote',
    remoteEntryUrl: 'https://cdn.mfe.company.internal/remotes/governance/remoteEntry.js',
    scope: 'GOVERNANCE',
    title: 'Governance, Payroll & Geofencing',
    description: 'Modul sistem untuk rekap penggajian, konfigurasi koordinat GPS kantor, jam shift, audit trail, dan RBAC.',
    iconName: 'FileSpreadsheet',
    routeKey: 'GOVERNANCE_MFE',
    subRoutes: [
      { key: 'REKAP_PAYROLL', label: 'Rekap Jam Kerja & Payroll', icon: 'DollarSign', permission: 'VIEW_PAYROLL_SUMMARY' },
      { key: 'GEOFENCE_SHIFT', label: 'Geofencing & Shift Kerja', icon: 'MapPin', permission: 'MANAGE_GEOFENCE_OFFICE' },
      { key: 'AUDIT_LOGS', label: 'Audit Trail Security Logs', icon: 'Lock', permission: 'VIEW_AUDIT_TRAILS' },
      { key: 'KONFIGURASI_AKSES', label: 'Konfigurasi Hak Akses Menu', icon: 'Sliders', permission: 'MANAGE_MENU_ACCESS' },
    ],
    status: 'HEALTHY',
    bundleSizeKb: 185.0,
    latencyMs: 15,
  },
];
